### ISSUE TITLE
Please add license in this repo

### ISSUE THREAD

**Issue by subham8907** [cloudcoroner/cromite_ubuntu#1]
Hello, I noticed that this repository does not currently have a license, which by default means "All Rights Reserved." If you'd like others to be able to download, use, and contribute to your work, consider adding an open-source license. Please note, this is friendly advice and not legal guidance—feel free to make a decision that best suits your needs.

**Comment by cloudcoroner** [comment]
thank you @subham8907 for pointing this out. GPL 3.0 license now added and added to new release.
